### ISSUE TITLE
Run go libp2p

### ISSUE THREAD

**Issue by Parviz-Makhkamov** [libp2p/npm-go-libp2p#1]
Hi! After installation, how I can use go-libp2p, for example, how a can call any function go-libp2p in own node js project ?

**Comment by achingbrain** [comment]
This module installs a command-line version of go-libp2p, mostly used for testing compatibility between js-libp2p and go-libp2p.

There is no programatic API, to do libp2p things, use [libp2p](https://www.npmjs.com/package/libp2p).
